# Generated by Django 5.0.4 on 2024-05-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
        migrations.AddField(
            model_name='history',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='delivery',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
