# Generated by Django 5.0.4 on 2024-05-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_history_options_history_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
